# Generated by Django 3.2 on 2021-05-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=8)),
                ('shares', models.DecimalField(decimal_places=8, max_digits=14)),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=13)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('entry_datetime', models.DateTimeField(blank=True, null=True)),
                ('exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('filled', models.BooleanField(default=False)),
                ('entry_fee', models.DecimalField(decimal_places=8, max_digits=14)),
                ('exit_fee', models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
