# Generated by Django 3.2 on 2021-05-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='paper_trade',
            field=models.BooleanField(default=True),
        ),
    ]
