# Generated by Django 3.2 on 2021-05-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trade_paper_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='coinbase_trade_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
